### PR TITLE
Added more Testcases 

### LINKED ISSUE #3: UTF-8 encoding
Great stuff, but unless I'm missing something, this will only work with ASCII text.

https://github.com/bottom-software-foundation/bottom-go/blob/ffac14ba06961de1dec70b095d2fe14753389653/bottom/bottom.go#L26

The spec states that it should be able to encode any valid UTF-8 characters, in which case we'd have to loop over the runes and not the bytes in the string.

PS: Go supports UTF-8 in its source files, so you should be able to insert the emoji directly instead of their escape  sequences.

### PR DESCRIPTION
**Pull request by K1ngjulien**
I added more Testcases which revealed that the decode doesn't seem to work quite right:

```
[~/code/bottom-go (main:3)]: go test ./...
--- FAIL: TestDecode (0.00s)
    bottom_test.go:31: expected: "がんばれ", got "ããã°ã       "
FAIL
FAIL    github.com/nihaals/bottom-go/bottom     0.001s
?       github.com/nihaals/bottom-go/cmd        [no test files]
FAIL
```

### CODE REVIEW

**Comment by K1ngjulien** [comment]
seems to work now. to be able to convert multi byte characters unicode chars all bytes need to be decoded before encoding them as utf-8 with `string()`

```
=== RUN   TestEncode
--- PASS: TestEncode (0.00s)
=== RUN   TestDecode
--- PASS: TestDecode (0.00s)
PASS
ok      github.com/nihaals/bottom-go/bottom     0.001s
?       github.com/nihaals/bottom-go/cmd        [no test files]
```

**Review by nihaals — APPROVED** [review]
I think having emotes in the test cases makes them way more readable but I want to stick to not having emoji in `bottom.go`.

**Comment by nihaals** [comment]
I'm not going to add the tests to CI yet as bottom should be getting a standard test suite at some point which can be used instead

**Comment by K1ngjulien** [comment]
> I think having emotes in the test cases makes them way more readable but I want to stick to not having emoji in `bottom.go`.

Alright, your decision. I still feel it also makes the other code more readable and almost all other implementations have emoji in the source :smile:.

**Comment by romdotdog** [comment]
I am having trouble getting in contact with other members of the org to come to a consensus on what should be done according to ambiguity in the spec. @nihaals, are you in the discord?

**Comment by nihaals** [comment]
> I am having trouble getting in contact with other members of the org to come to a consensus on what should be done according to ambiguity in the spec. @nihaals, are you in the discord?

I'm not no, I have no spare server slots. What ambiguity is there in the spec other than null byte? I don't think there are any ambiguities related to this PR

**Comment by romdotdog** [comment]
> What ambiguity is there in the spec other than null byte?

whether all implementations should decode regardless of the presence of a trailing byte separator, whether "invalid" bottom such as `,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈` should be decodable, etc.
Since @kaylynn234 is completely inactive and is not set on assigning a new owner of the org, we should have a discussion on how to modify the spec.

**Comment by nihaals** [comment]
I don't think that should block this PR from being merged

**Comment by romdotdog** [comment]
I am not saying it shouldn't be merged, but, like you said, a standardized testing suite should be the way to go.

**Comment by K1ngjulien** [comment]
:tada: 


> whether all implementations should decode regardless of the presence of a trailing byte separator, whether "invalid" bottom such as `,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,👉👈` should be decodable, etc.

well the spec says bytes should be ordered to speed up decoding. encoding like this is definitly slower :)
>Note the ordering of characters within groups. Groups of value characters must be in descending order. While character order (within groups) technically does not affect the output in any way, arbitrary ordering can encroach significantly on decoding speed and is considered both illegal and bad form.

**Comment by nihaals** [comment]
Thanks!

**Comment by K1ngjulien** [comment]
> Thanks!

You're welcome. Glad to be a contributer to such a world changing project :smile:

**Pull request merged**
