### PR TITLE
Add file IO into CLI

### LINKED ISSUE #2: Support files and stdin

### PR DESCRIPTION
**Pull request by diamondburned**
This pull request adds the flag `-o` to set the output; it also accepts the first argument for the input. Both IO arguments can take `-` for stdio.

Usage:

```
―❤―▶ echo "bruh moment" | go run ./cmd/bottom/ | go run ./cmd/bottom -d 
bruh moment
```

This pull request also moved the CLI into `./cmd/bottom` for idiomaticity. The command to install it would therefore be:

```sh
go get github.com/bottom-software-foundation/bottom-go/cmd/bottom
```

#### API breakage:

This pull request breaks the existing `EncodeTo` function signature to remove the total bytes written. This is because the function will either write everything successfully or error out, and the caller can manually keep track of the written length by wrapping the writer.

---

This PR closes #2.

### CODE REVIEW

**Comment by K1ngjulien** [comment]
cool! this doesn't support passing in an input string directly, correct? (i.e `bottom "bruh moment"` )

**Comment by diamondburned** [comment]
> cool! this doesn't support passing in an input string directly, correct? (i.e `bottom "bruh moment"` )

It doesn't, so you'll have to use `./bottom <<< "string"`. The first argument is used for the input file.

**Comment by nihaals** [comment]
I think we should Go for something like https://github.com/bottom-software-foundation/bottom-go/issues/2#issuecomment-777868103 as it feels more familiar and is much nicer when not wanting to encode a file

**Comment by diamondburned** [comment]
> I think we should Go for something like [#2 (comment)](https://github.com/bottom-software-foundation/bottom-go/issues/2#issuecomment-777868103) as it feels more familiar and is much nicer when not wanting to encode a file

I'm not sure what's more familiar about that. Almost any Unix tools I know of does something similar:

```
―❤―▶ base64 --help
Usage: base64 [OPTION]... [FILE]
Base64 encode or decode FILE, or standard input, to standard output.

With no FILE, or when FILE is -, read standard input.

Mandatory arguments to long options are mandatory for short options too.
  -d, --decode          decode data

―❤―▶ sha256sum --help
Usage: sha256sum [OPTION]... [FILE]...

―❤―▶ cat --help
Usage: cat [OPTION]... [FILE]...
```

Everybody who's remotely familiar with the terminal knows the `echo text | command` construct to feed into stdin.

**Comment by nihaals** [comment]
GNU's `base64` was actually what I originally based the design on despite other implementations using different syntax so I agree it makes sense.

I've seen a mix, most of the "standard" tools use files but there's still popular tools that either support both or you prefix files with a flag (ffmpeg comes to mind).

I don't have a strong preference but based on feedback I'm absolutely willing to reconsider. If we stick to `base64`, which after you bringing it up has made me change my mind towards using only files, then only allowing files is the way to go and will probably make it easier to understand for new users (we can also specify this inspiration in the README). A potential argument is that the majority of uses of bottom is for a quick encode/decode, so requiring a file might just make it more annoying.

@K1ngjulien what do you think?

**Comment by K1ngjulien** [comment]
> I'm not sure what's more familiar about that. Almost any Unix tools I know of does something similar

Yeah you're right, I hadn't really thought of that. The standard unix way is definitely a more familiar version and the way to go.

Tho I agree that most people will be using bottom in a one off fashon for quck encodes. So maybe an additional flag for passing in strings directly could be added, which would error when also passing a filename at the same time:

```
$ bottom -t "input text" 
<bottom text>
$ bottom input.txt -t "hello"
Error
```
This way you wouldn't have to pipe in all your text from echo

Thougts?

**Comment by diamondburned** [comment]
> > I'm not sure what's more familiar about that. Almost any Unix tools I know of does something similar
> 
> Yeah you're right, I hadn't really thought of that. The standard unix way is definitely a more familiar version and the way to go.
> 
> Tho I agree that most people will be using bottom in a one off fashon for quck encodes. So maybe an additional flag for passing in strings directly could be added, which would error when also passing a filename at the same time:
> 
> ```
> $ bottom -t "input text" 
> <bottom text>
> $ bottom input.txt -t "hello"
> Error
> ```
> 
> This way you wouldn't have to pipe in all your text from echo
> 
> Thougts?

Is doing `echo "text" | bottom` or `bottom <<< "text"` that much work?

**Comment by K1ngjulien** [comment]
TIL about `command <<< "string"` 😅😅

Well in that case, ship it🚀

**Comment by nihaals** [comment]
Related #7

**Pull request merged**
